module ActiveStoragePath
  extend ActiveSupport::Concern

  class_methods do
    def has_one_attached_with(name, path:) # rubocop:disable Naming/PredicateName
      has_one_attached name

      define_method "#{name}=" do |attachable|
        action = super attachable

        return action unless action.is_a? ActiveStorage::Attached::Changes::CreateOne
        return action unless action.blob.service_name == :local

        # This is how it is generated by default
        original_key = action.blob.class.generate_unique_secure_token

        # The key is used for path + filename when Local Storage is used. Append path.
        action.blob.key = File.join(instance_exec(&path), original_key)

        action
      end
    end
  end
end